# Generated by Django 3.2.16 on 2022-11-07 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_section_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_section_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_section_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.CharField(max_length=255)),
                ('number', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/%Y/%m/%d')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_question_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_question_deleted', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_question_question', to='quiz.section')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_question_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answer_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answer_deleted', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answer_answer', to='quiz.question')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answer_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
